global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "100.82.36.47:9100"
          - "100.103.185.8:9100"
          - "100.121.171.72:9100"
          - "100.119.217.113:9100"